"""Small, reviewed cases for optional cross-engine comparison.

The safe intersection intentionally avoids stereochemistry, ambiguous
aromaticity models, and toolkit-specific extensions. Boundary cases document
differences but do not turn an implementation majority into a specification.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple


@dataclass(frozen=True)
class DifferentialCase:
    case_id: str
    smarts: str
    smiles: str
    group: str
    expected_matched: Optional[bool]
    compare_enumeration: bool
    features: Tuple[str, ...]
    evidence_tier: str
    notes: str = ""
    expected_query_accepted: Optional[bool] = True
    equivalence_key: Optional[str] = None
    equivalence_variant: Optional[str] = None


CASES = (
    DifferentialCase(
        "safe.atom.element",
        "C",
        "CCO",
        "safe_intersection",
        True,
        True,
        ("element",),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.atom.atomic_number",
        "[#8]",
        "CCO",
        "safe_intersection",
        True,
        True,
        ("atomic_number",),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.atom.wildcard",
        "*",
        "N",
        "safe_intersection",
        True,
        True,
        ("wildcard",),
        "tier_1_curated",
    ),
    DifferentialCase(
        "regression.bare_aromatic.positive",
        "a",
        "c1ccccc1",
        "safe_intersection",
        True,
        True,
        ("bare_aromatic_wildcard", "regression"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "regression.bare_aromatic.negative",
        "a",
        "C",
        "safe_intersection",
        False,
        True,
        ("bare_aromatic_wildcard", "near_negative", "regression"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "regression.bare_aliphatic.positive",
        "A",
        "C",
        "safe_intersection",
        True,
        True,
        ("bare_aliphatic_wildcard", "regression"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "regression.bare_aliphatic.negative",
        "A",
        "c1ccccc1",
        "safe_intersection",
        False,
        True,
        ("bare_aliphatic_wildcard", "near_negative", "regression"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.atom.or",
        "[N,O]",
        "CCN",
        "safe_intersection",
        True,
        True,
        ("atom_logic", "or"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.atom.not",
        "[!#6]",
        "CCO",
        "safe_intersection",
        True,
        True,
        ("atom_logic", "not"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.atom.map_metadata",
        "[C:7]",
        "CO",
        "safe_intersection",
        True,
        True,
        ("atom_map",),
        "tier_1_curated",
        "Atom maps are metadata and do not constrain matching.",
    ),
    DifferentialCase(
        "safe.atom.hydrogen_count",
        "[O;H1]",
        "CCO",
        "safe_intersection",
        True,
        True,
        ("hydrogen_count",),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.bond.single",
        "C-C",
        "CCO",
        "safe_intersection",
        True,
        True,
        ("single_bond",),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.bond.double_negative",
        "C=C",
        "CC",
        "safe_intersection",
        False,
        True,
        ("double_bond", "near_negative"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.bond.triple",
        "C#N",
        "CC#N",
        "safe_intersection",
        True,
        True,
        ("triple_bond",),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.bond.any",
        "C~O",
        "C=O",
        "safe_intersection",
        True,
        True,
        ("any_bond",),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.aromatic.bond",
        "c:c",
        "c1ccccc1",
        "safe_intersection",
        True,
        True,
        ("aromatic_atom", "aromatic_bond"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "regression.aromatic.implicit",
        "cc",
        "c1ccccc1",
        "safe_intersection",
        True,
        True,
        ("aromatic_atom", "implicit_bond", "regression"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "regression.aromatic.explicit_single",
        "c-c",
        "c1ccccc1",
        "safe_intersection",
        False,
        True,
        ("aromatic_atom", "single_bond", "near_negative", "regression"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "regression.aromatic.explicit_double",
        "c=c",
        "c1ccccc1",
        "safe_intersection",
        False,
        True,
        ("aromatic_atom", "double_bond", "near_negative", "regression"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "regression.atomic_number.explicit_single",
        "[#6]-[#6]",
        "c1ccccc1",
        "safe_intersection",
        False,
        True,
        ("atomic_number", "single_bond", "near_negative", "regression"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "regression.atomic_number.explicit_double",
        "[#6]=[#6]",
        "c1ccccc1",
        "safe_intersection",
        False,
        True,
        ("atomic_number", "double_bond", "near_negative", "regression"),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.ring.membership",
        "[R]",
        "C1CCCCC1",
        "safe_intersection",
        True,
        True,
        ("ring_membership",),
        "tier_1_curated",
    ),
    DifferentialCase(
        "safe.recursive.anchored",
        "[$([#6]-[#8])]",
        "CCO",
        "safe_intersection",
        True,
        True,
        ("recursive",),
        "tier_1_curated",
    ),
    DifferentialCase(
        "invalid.bracket.unclosed",
        "[C",
        "C",
        "invalid_syntax",
        None,
        False,
        ("unclosed_bracket",),
        "tier_1_curated",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "invalid.bond.dangling",
        "C-",
        "C",
        "invalid_syntax",
        None,
        False,
        ("dangling_bond",),
        "tier_1_curated",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "regression.invalid.empty",
        "",
        "C",
        "invalid_syntax",
        None,
        False,
        ("empty_query", "regression"),
        "tier_1_curated",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "regression.invalid.whitespace",
        " \t ",
        "C",
        "invalid_syntax",
        None,
        False,
        ("empty_query", "whitespace", "regression"),
        "tier_1_curated",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "regression.invalid.dot_only",
        ".",
        "C",
        "invalid_syntax",
        None,
        False,
        ("empty_component", "regression"),
        "tier_1_curated",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "regression.invalid.leading_dot",
        ".C",
        "C",
        "invalid_syntax",
        None,
        False,
        ("empty_component", "regression"),
        "tier_1_curated",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "regression.invalid.trailing_dot",
        "C.",
        "C",
        "invalid_syntax",
        None,
        False,
        ("empty_component", "regression"),
        "tier_1_curated",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "regression.invalid.double_dot",
        "C..O",
        "CO",
        "invalid_syntax",
        None,
        False,
        ("empty_component", "regression"),
        "tier_1_curated",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "regression.invalid.self_loop",
        "C11",
        "C",
        "invalid_syntax",
        None,
        False,
        ("self_loop", "ring_closure", "regression"),
        "tier_1_curated",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "boundary.disconnected",
        "C.O",
        "CC.O",
        "dialect_boundary",
        True,
        False,
        ("disconnected_query",),
        "tier_2_differential",
        "Component grouping and disconnected-query behavior vary by engine.",
    ),
    DifferentialCase(
        "boundary.isotope",
        "[13C]",
        "[13CH4]",
        "unsupported_feature",
        None,
        False,
        ("isotope",),
        "tier_3_documented",
        "Hotpot documents isotope queries as unsupported.",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "boundary.chirality",
        "[C@H](F)Cl",
        "N[C@H](F)Cl",
        "unsupported_feature",
        None,
        False,
        ("chirality",),
        "tier_3_documented",
        "Hotpot documents atom chirality as unsupported.",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "boundary.directional_bond",
        "F/C=C/F",
        "F/C=C/F",
        "unsupported_feature",
        None,
        False,
        ("directional_bond",),
        "tier_3_documented",
        "Hotpot documents directional bonds as unsupported.",
        expected_query_accepted=False,
    ),
    DifferentialCase(
        "extension.metal",
        "[M]",
        "[Na+]",
        "hotpot_extension",
        True,
        False,
        ("metal",),
        "tier_3_documented",
    ),
    DifferentialCase(
        "extension.lanthanide",
        "[Ln]",
        "[La+3]",
        "hotpot_extension",
        True,
        False,
        ("lanthanide",),
        "tier_3_documented",
    ),
    DifferentialCase(
        "extension.actinide",
        "[An]",
        "[U]",
        "hotpot_extension",
        True,
        False,
        ("actinide",),
        "tier_3_documented",
    ),
    DifferentialCase(
        "extension.period",
        "[NP3]",
        "Cl",
        "hotpot_extension",
        True,
        False,
        ("period",),
        "tier_3_documented",
    ),
    DifferentialCase(
        "extension.group",
        "[NG17]",
        "Cl",
        "hotpot_extension",
        True,
        False,
        ("group",),
        "tier_3_documented",
    ),
)


ELEMENT_SYMBOLS = (
    "H",
    "He",
    "Li",
    "Be",
    "B",
    "C",
    "N",
    "O",
    "F",
    "Ne",
    "Na",
    "Mg",
    "Al",
    "Si",
    "P",
    "S",
    "Cl",
    "Ar",
    "K",
    "Ca",
    "Sc",
    "Ti",
    "V",
    "Cr",
    "Mn",
    "Fe",
    "Co",
    "Ni",
    "Cu",
    "Zn",
    "Ga",
    "Ge",
    "As",
    "Se",
    "Br",
    "Kr",
    "Rb",
    "Sr",
    "Y",
    "Zr",
    "Nb",
    "Mo",
    "Tc",
    "Ru",
    "Rh",
    "Pd",
    "Ag",
    "Cd",
    "In",
    "Sn",
    "Sb",
    "Te",
    "I",
    "Xe",
    "Cs",
    "Ba",
    "La",
    "Ce",
    "Pr",
    "Nd",
    "Pm",
    "Sm",
    "Eu",
    "Gd",
    "Tb",
    "Dy",
    "Ho",
    "Er",
    "Tm",
    "Yb",
    "Lu",
    "Hf",
    "Ta",
    "W",
    "Re",
    "Os",
    "Ir",
    "Pt",
    "Au",
    "Hg",
    "Tl",
    "Pb",
    "Bi",
    "Po",
    "At",
    "Rn",
    "Fr",
    "Ra",
    "Ac",
    "Th",
    "Pa",
    "U",
    "Np",
    "Pu",
    "Am",
    "Cm",
    "Bk",
    "Cf",
    "Es",
    "Fm",
    "Md",
    "No",
    "Lr",
    "Rf",
    "Db",
    "Sg",
    "Bh",
    "Hs",
    "Mt",
    "Ds",
    "Rg",
    "Cn",
    "Nh",
    "Fl",
    "Mc",
    "Lv",
    "Ts",
    "Og",
)


def _element_equivalence_cases() -> Tuple[DifferentialCase, ...]:
    cases = []
    for atomic_number, symbol in enumerate(ELEMENT_SYMBOLS, start=1):
        key = f"element.{atomic_number:03d}.{symbol}"
        target = f"[{symbol}]"
        common = {
            "smiles": target,
            "group": "element_equivalence",
            "expected_matched": True,
            "compare_enumeration": True,
            "evidence_tier": "tier_1_periodic_identity",
            "equivalence_key": key,
        }
        cases.append(
            DifferentialCase(
                case_id=f"matrix.{key}.atomic_number",
                smarts=f"[#{atomic_number}]",
                features=("element_matrix", "atomic_number"),
                equivalence_variant="atomic_number",
                **common,
            )
        )
        cases.append(
            DifferentialCase(
                case_id=f"matrix.{key}.symbol",
                smarts=target,
                features=("element_matrix", "element_symbol"),
                equivalence_variant="symbol",
                **common,
            )
        )
    return tuple(cases)


CASES += _element_equivalence_cases()
