"""Shared policy constants for force-field workflows."""


__all__ = ()


_BOND_RING_MAX_SIZE = 16


# Deterministic metal-only placement policy used by coordination restoration.
_METAL_RELOCATION_MAX_CANDIDATES = 96
_METAL_RELOCATION_SPHERE_DIRECTION_COUNT = 32
_METAL_RELOCATION_COORDINATION_DISTANCE_SCALE = 1.0
_METAL_RELOCATION_COORDINATION_DISTANCE_RATIO_MIN = 0.70
_METAL_RELOCATION_COORDINATION_DISTANCE_RATIO_MAX = 1.50
_METAL_RELOCATION_MIN_ATOM_CLEARANCE = 0.35
_METAL_RELOCATION_MIN_BOND_CLEARANCE = 0.50
_METAL_RELOCATION_DIRECTION_EPSILON = 1.0e-12
_METAL_RELOCATION_DUPLICATE_TOLERANCE = 1.0e-8
