"""Shared force-field API composition for the versioned facades."""

from .acceptance import evaluate_structure_acceptance, is_structure_accepted
from .contracts import (
    AcceptanceCheck,
    AcceptanceLevel as AcceptanceLevel,
    Build3DReport,
    BuildAndOptimizeReport,
    BuildTimeoutError,
    BuildWorkerError,
    BuildWorkerResult,
    CandidateRejection,
    ComplexBuildDiagnostics,
    ComplexBuildError,
    ComplexBuildReport,
    ComplexBuildTimeoutError,
    ComplexBuildWarning,
    ComplexBuildWorkerError,
    CoordinationBondRestorationReport,
    CoordinationEnvironment,
    CoordinationGeometryCandidate,
    CoordinationGeometryResult,
    ForceFieldAcceptanceEvidence,
    ForceFieldDiagnosticValue,
    ForceFieldError,
    ForceFieldRunReport,
    ForceFieldSetupError,
    ForceFieldSetupReport,
    ForceFieldStage as ForceFieldStage,
    ForceFieldValidationReport,
    ForceFieldWorkflowReport,
    GeometryQualityError,
    GeometryQualityWarning,
    OptimizationAlgorithm,
    RingUntanglingReport,
    StructureAcceptanceThresholds,
    TerminationReason,
    TrajectoryPath,
)
from .coordination import (
    collect_coordination_environments,
    prepare_coordination_geometry,
)
from .coordinates import perturb
from .topology import (
    AtomTopologySignature,
    BondTopologySignature,
    TopologyReference,
    capture_topology,
)
from .trajectory import (
    AtomIdentity,
    BondTopology,
    BondTopologyRevision,
    CoordinationFrameEvidence,
    ForceFieldFrame,
    ForceFieldTrajectory,
    ForceFieldTrajectoryArchive,
    FrameEvidence,
    OptimizationFrameEvidence,
    RingFrameEvidence,
    TrajectoryEvent,
    TrajectoryStage,
    TrajectoryStart,
)
from .workflows import (
    _build3d_workflow as _build3d_workflow,
    _build_and_optimize_workflow as _build_and_optimize_workflow,
    _build_complex3d_workflow as _build_complex3d_workflow,
    _complexes_build_workflow as _complexes_build_workflow,
    auto_optimize,
    build3d,
    build_and_optimize,
    build_complex3d,
    complexes_build,
    optimize,
    optimize_complex,
)


__all__ = (
    "TrajectoryPath",
    "TrajectoryStart",
    "TrajectoryStage",
    "TrajectoryEvent",
    "AtomIdentity",
    "BondTopology",
    "BondTopologyRevision",
    "RingFrameEvidence",
    "CoordinationFrameEvidence",
    "OptimizationFrameEvidence",
    "FrameEvidence",
    "ForceFieldFrame",
    "ForceFieldTrajectory",
    "ForceFieldTrajectoryArchive",
    "OptimizationAlgorithm",
    "TerminationReason",
    "ForceFieldDiagnosticValue",
    "ForceFieldRunReport",
    "Build3DReport",
    "CandidateRejection",
    "RingUntanglingReport",
    "CoordinationBondRestorationReport",
    "ComplexBuildDiagnostics",
    "BuildWorkerResult",
    "ForceFieldWorkflowReport",
    "BuildAndOptimizeReport",
    "ComplexBuildReport",
    "ForceFieldSetupReport",
    "AcceptanceCheck",
    "StructureAcceptanceThresholds",
    "ForceFieldAcceptanceEvidence",
    "AtomTopologySignature",
    "BondTopologySignature",
    "TopologyReference",
    "ForceFieldValidationReport",
    "CoordinationEnvironment",
    "CoordinationGeometryCandidate",
    "CoordinationGeometryResult",
    "ForceFieldError",
    "ForceFieldSetupError",
    "BuildWorkerError",
    "BuildTimeoutError",
    "ComplexBuildError",
    "ComplexBuildWarning",
    "ComplexBuildWorkerError",
    "ComplexBuildTimeoutError",
    "GeometryQualityError",
    "GeometryQualityWarning",
    "capture_topology",
    "evaluate_structure_acceptance",
    "is_structure_accepted",
    "perturb",
    "collect_coordination_environments",
    "prepare_coordination_geometry",
    "build3d",
    "optimize",
    "build_complex3d",
    "optimize_complex",
    "complexes_build",
    "build_and_optimize",
    "auto_optimize",
)
