name: Test Workflow

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: To workdir
        uses: actions/checkout@v4

      - name: Cache conda
        uses: actions/cache@v4
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml', 'pyproject.toml') }}

      - name: Set up conda-env
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: hp
          auto-activate: false
          auto-update-conda: false
          environment-file: environment.yml
          use-only-tar-bz2: true
          pkgs-dirs: ~/conda_pkgs_dir

      - run: |
          conda info
          conda list
        working-directory: ${{ github.workspace }}

      - name: Install coverage
        run: python -m pip install coverage

      - name: Run tests by coverage
        run: |
          coverage run --source hotpot -m unittest
          coverage xml -i
        env:
          COVERAGE_RUN: True

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
